theme: Minimal theme
title: Pacemaker Framework Interactive
logo: /assets/img/logo.png
description: 
seal: false
background-image: img src="images/custom gingham final.png"
background-repeat: repeat;
